### ISSUE TITLE
Small corrections, adjustments, improvement idea

### ISSUE THREAD

**Issue by thmcon** [tbblake/speedtest2Zabbix#1]
Hi,

amazing work! brilliant! Thanks a lot!

During my installation of your script I found a few small things you could improve, if you like.

1) In the README for the installation you could mention that the script needs to get executable permissions (chmod) after download.

2) In the script itself the variable SPDHOST is shown with example value x.x.x.x => in my experiences it worked when I added SPDHOST="zabbix server name who receives the speedtest results" - maybe the example value of x.x.x.x is leading in the wrong direction

3) Idea for improvement: in my scenario I have to pass parameters to the speedtest binary. Therefore I adjusted your script for my needs as following:

added a variable:
```
# Speedtest Params
SPEEDTESTPARAMS="-i 10.10.100.14"
```

And I adjusted the following line
`$TIMEOUT $TIMEOUTTIME $SPEEDTEST -f json 2>/dev/null > $OUTFILE`
to 
`$TIMEOUT $TIMEOUTTIME $SPEEDTEST $SPEEDTESTPARAMS -f json 2>/dev/null > $OUTFILE`

I like you solution very much!
Best,
Thomas

**Comment by tbblake** [comment]
Both great suggestions thank you.  I’ll add them when I’m near a computer later!

**Comment by tbblake** [comment]
Great suggestions I updated record_speedtest.sh with them.  I'm actually mid-process with putting all of this into the official zabbix repo, so once it's accepted I'll start another pull request with these changes over there --> https://github.com/tbblake/community-templates/tree/speedtest/Applications/Template_App_Speedtest_Wan
